export const SEARCH_CITY = 'SEARCH_CITY';

export const SEARCH_CITY_REQUEST = 'SEARCH_CITY_REQUEST';
export const SEARCH_CITY_SUCCESS = 'SEARCH_CITY_SUCCESS';
export const SEARCH_CITY_FAIL = 'SEARCH_CITY_FAIL';

export const ADD_HISTORY = 'ADD_HISTORY';
