export const ADD_TO_FAVORITES_REQUEST = "ADD_TO_FAVORITES_REQUEST";
export const ADD_TO_FAVORITES_SUCCESS = "ADD_TO_FAVORITES_SUCCESS";
export const ADD_TO_FAVORITES_ERROR = "ADD_TO_FAVORITES_ERROR";

export const FAVORITE_PROPERTIES = "FAVORITE_PROPERTIES";