export const GET_PROPERTY_REQUEST = "GET_PROPERTY_REQUEST";
export const GET_PROPERTY_SUCCESS = "GET_PROPERTY_SUCCESS";
export const GET_PROPERTY_ERROR = "GET_PROPERTY_ERROR";

export const GET_BUILDING_SUCCESS = "GET_BUILDING_SUCCESS";

export const REQUEST_PROPERTY = "REQUEST_PROPERTY";
